/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package detodosa;

import java.util.TreeSet;

/**
 *
 * @author ferben007
 */
public class MenuGeneral extends javax.swing.JFrame {
    private static int contador = 0;
public static TreeSet<Producto> listaProducto=new TreeSet<>();
    /**
     * Creates new form MenuGeneral
     */
    public MenuGeneral() {
        
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmProducto = new javax.swing.JMenuItem();
        jmCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmPorPrecio = new javax.swing.JMenuItem();
        jmCategoria = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmProducto.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmProducto.setText("Productos");
        jmProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmProductoActionPerformed(evt);
            }
        });
        jMenu1.add(jmProducto);

        jmCliente.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmCliente.setText("Clientes");
        jmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N

        jmPorPrecio.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmPorPrecio.setText("Por Precio");
        jmPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorPrecio);

        jmCategoria.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jmCategoria.setText("Pro Categoria");
        jmCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCategoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jmCategoria);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem3.setText("Por Nombre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        PorNombre pn =new PorNombre();
        pn.setVisible(true);
        escritorio.add(pn);
        escritorio.moveToFront(pn);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmProductoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        CargaDeProductos pn =new CargaDeProductos();
        pn.setVisible(true);
        escritorio.add(pn);
        escritorio.moveToFront(pn);
        pn.setLocation(50, 50);
    }//GEN-LAST:event_jmProductoActionPerformed

    private void jmPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorPrecioActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        PorPrecio pn =new PorPrecio();
        pn.setVisible(true);
        escritorio.add(pn);
        escritorio.moveToFront(pn);
    }//GEN-LAST:event_jmPorPrecioActionPerformed

    private void jmCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCategoriaActionPerformed
        // TODO add your handling code here:
            escritorio.removeAll();
        escritorio.repaint();
        PorRubro pn =new PorRubro();
        pn.setVisible(true);
        escritorio.add(pn);
        escritorio.moveToFront(pn);
    }//GEN-LAST:event_jmCategoriaActionPerformed

    private void jmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmClienteActionPerformed
        // TODO add your handling code here:
               escritorio.removeAll();
        escritorio.repaint();
        cargaCliente pn =new cargaCliente();
        pn.setVisible(true);
        escritorio.add(pn);
        escritorio.moveToFront(pn);
    }//GEN-LAST:event_jmClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmCategoria;
    private javax.swing.JMenuItem jmCliente;
    private javax.swing.JMenuItem jmPorPrecio;
    private javax.swing.JMenuItem jmProducto;
    // End of variables declaration//GEN-END:variables
    private static String generarCodigo(){
        String codigo = String.format("%04d", contador);
        contador++;
        return codigo;
    } 
    private void cargarProductos(){
    listaProducto.add(new Producto(10, "Yerba", 560.99, 10, Categoria.COMESTIBLES));
    listaProducto.add(new Producto(11, "Azucar", 460.99, 15, Categoria.COMESTIBLES));
    listaProducto.add(new Producto(12, "Lavandina", 760.99, 3, Categoria.LIMPIEZA));
    listaProducto.add(new Producto(13, "Detergente", 360.99, 5, Categoria.LIMPIEZA));
    listaProducto.add(new Producto(14, "Jabon", 280.99, 7, Categoria.PERFUMERIA));
}
}
